# Generated by Django 4.2.4 on 2023-10-16 14:16

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('main_card', models.BooleanField(default=False)),
                ('bank_ico', models.FileField(default='images/bankIcons/question.svg', upload_to='images/bankIcons')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='images/category_icon')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('color_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/delivery_point')),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('coord_x', models.FloatField()),
                ('coord_y', models.FloatField()),
                ('seleceted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/deliveryslider')),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('size_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SliderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_photo', models.ImageField(upload_to='images/slider')),
                ('medium_photo', models.ImageField(upload_to='images/slider')),
                ('small_photo', models.ImageField(upload_to='images/slider')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='testApi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_photo', models.ImageField(upload_to='images/product_photo')),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('count_feedbacks', models.IntegerField()),
                ('characteristics', models.JSONField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='testApi.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OnRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField(default=0)),
                ('bank_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.bankcards')),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.deliverypoints')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('isChecked', models.BooleanField(default=False)),
                ('totalCount', models.IntegerField(default=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.BooleanField(default=False)),
                ('size', models.BooleanField(default=False)),
                ('fields', models.JSONField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testApi.category')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='testApi.subcategory')),
            ],
            options={
                'unique_together': {('category', 'subcategory')},
            },
        ),
    ]
