# Generated by Django 4.2.4 on 2023-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_photo', models.ImageField(upload_to='images/slider')),
                ('medium_photo', models.ImageField(upload_to='images/slider')),
                ('small_photo', models.ImageField(upload_to='images/slider')),
            ],
        ),
    ]
