# Generated by Django 4.2.4 on 2023-10-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0002_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_feedbacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
