# Generated by Django 4.2.4 on 2023-08-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0002_sliderphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_photo', models.ImageField(upload_to='images/product_photo')),
                ('price', models.IntegerField(max_length=10)),
                ('rating', models.IntegerField(max_length=1)),
                ('count_feedbacks', models.IntegerField(max_length=10)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='testApi.subcategory')),
            ],
        ),
    ]
