# Generated by Django 4.2.4 on 2023-08-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_feedbacks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
