# Generated by Django 4.2.4 on 2023-08-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0004_alter_product_count_feedbacks_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=1, upload_to='images/category_icon'),
            preserve_default=False,
        ),
    ]
