# Generated by Django 4.2.4 on 2023-10-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0004_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/product_photo')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_photo',
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ManyToManyField(to='testApi.productphoto'),
        ),
    ]
