# Generated by Django 4.2.4 on 2023-10-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0005_productphoto_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_photo',
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_photo', to='testApi.productphoto'),
            preserve_default=False,
        ),
    ]
