# Generated by Django 4.2.4 on 2023-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0006_deliverypoints_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndreyDelivey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/andreyphoto')),
            ],
        ),
    ]
