# Generated by Django 4.2.4 on 2023-10-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0007_alter_product_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_photo',
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ManyToManyField(to='testApi.productphoto'),
        ),
    ]
