# Generated by Django 4.2.4 on 2023-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0008_remove_product_product_photo_product_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(default=1, upload_to='images/product_photo'),
            preserve_default=False,
        ),
    ]
