# Generated by Django 4.2.4 on 2023-09-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0008_bankcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcards',
            name='bank_ico',
            field=models.FileField(default='images/bankIcons/question.svg', upload_to='images/bankIcons'),
        ),
    ]
