# Generated by Django 4.2.4 on 2023-10-24 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0009_product_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPointPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/delivery_point')),
            ],
        ),
        migrations.RenameField(
            model_name='deliverypoints',
            old_name='photo',
            new_name='main_photo',
        ),
        migrations.CreateModel(
            name='MyDeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testApi.deliverypoints')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPointComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=300)),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testApi.deliverypoints')),
            ],
        ),
        migrations.AddField(
            model_name='deliverypoints',
            name='photos',
            field=models.ManyToManyField(to='testApi.deliverypointphoto'),
        ),
    ]
