# Generated by Django 4.2.4 on 2023-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0009_bankcards_bank_ico'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/deliveryslider')),
            ],
        ),
    ]
