# Generated by Django 4.2.4 on 2023-10-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
