# Generated by Django 4.2.4 on 2023-10-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0010_deliverypointphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypoints',
            name='seleceted',
        ),
    ]
