# Generated by Django 4.2.4 on 2023-10-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0011_cart_count_cart_ischecked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AndreyDelivey',
        ),
    ]
