# Generated by Django 4.2.4 on 2023-11-25 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0013_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.product'),
        ),
        migrations.AlterField(
            model_name='deliverypoints',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
