# Generated by Django 4.2.4 on 2023-10-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0014_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypoints',
            name='seleceted',
            field=models.BooleanField(default=False),
        ),
    ]
