# Generated by Django 4.2.4 on 2023-12-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0014_alter_cart_product_alter_deliverypoints_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='onroad',
            name='totalCount',
            field=models.IntegerField(default=0),
        ),
    ]
