# Generated by Django 4.2.4 on 2023-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0015_deliverypoints_seleceted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalCoint',
            field=models.IntegerField(default=15),
        ),
    ]
