# Generated by Django 4.2.4 on 2023-12-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0015_onroad_totalcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='onroad',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='testApi.colormodel'),
        ),
        migrations.AddField(
            model_name='onroad',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='testApi.sizemodel'),
        ),
    ]
