# Generated by Django 4.2.4 on 2023-10-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0016_cart_totalcoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='totalCoint',
            new_name='totalCount',
        ),
    ]
