# Generated by Django 4.2.4 on 2023-10-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0017_rename_totalcoint_cart_totalcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('totalPrice', models.IntegerField(default=0)),
                ('bank_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.bankcards')),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.deliverypoints')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.product')),
            ],
        ),
    ]
