# Generated by Django 4.2.4 on 2024-01-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0017_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profilee',
        ),
    ]
