# Generated by Django 4.2.4 on 2023-10-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0018_onroad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onroad',
            name='count',
        ),
    ]
