# Generated by Django 4.2.4 on 2024-01-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0018_rename_profile_profilee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilee',
            new_name='UserProfile',
        ),
    ]
