# Generated by Django 4.2.4 on 2024-01-31 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0019_rename_profilee_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
