# Generated by Django 4.2.4 on 2023-10-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0010_deliveryslider'),
        ('testApi', '0019_remove_onroad_count'),
    ]

    operations = [
    ]
