# Generated by Django 4.2.4 on 2023-10-15 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0022_alter_productcharacteristics_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristics',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testApi.category'),
        ),
    ]
