# Generated by Django 4.2.4 on 2024-02-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0023_bankcards_user_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverypointcomments',
            unique_together={('user', 'delivery_point')},
        ),
    ]
