# Generated by Django 4.2.4 on 2023-10-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0023_alter_productcharacteristics_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristics',
            name='subcategory',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_id': models.F('category_id')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='testApi.subcategory'),
        ),
    ]
