# Generated by Django 4.2.4 on 2023-10-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0024_alter_productcharacteristics_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristics',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.category'),
        ),
    ]
