# Generated by Django 4.2.4 on 2024-02-02 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0024_alter_deliverypointcomments_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoints',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
