# Generated by Django 4.2.4 on 2023-10-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0026_alter_productcharacteristics_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourNewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.subcategory')),
            ],
            options={
                'unique_together': {('category', 'subcategory')},
            },
        ),
    ]
