# Generated by Django 4.2.4 on 2024-02-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0027_userpurchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypoints',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='testApi.deliverypoints'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MyDeliveryPoint',
        ),
    ]
