# Generated by Django 4.2.4 on 2023-10-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0027_yournewmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yournewmodel',
            options={'verbose_name': 'Your New Model', 'verbose_name_plural': 'Your New Models'},
        ),
        migrations.AlterUniqueTogether(
            name='yournewmodel',
            unique_together=set(),
        ),
    ]
