# Generated by Django 4.2.4 on 2024-02-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0028_remove_deliverypoints_user_customuser_delivery_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='delivery_point',
        ),
    ]
