# Generated by Django 4.2.4 on 2023-10-15 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0028_alter_yournewmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yournewmodel',
            name='subcategory',
            field=models.ForeignKey(limit_choices_to={'category': models.F('category')}, on_delete=django.db.models.deletion.CASCADE, to='testApi.subcategory'),
        ),
    ]
