# Generated by Django 4.2.4 on 2023-10-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0029_alter_yournewmodel_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourNewModel',
        ),
    ]
