# Generated by Django 4.2.4 on 2024-02-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0030_customuser_delivery_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='testApi.deliverypoints'),
        ),
    ]
