# Generated by Django 4.2.4 on 2024-02-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0031_alter_customuser_delivery_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
    ]
