# Generated by Django 4.2.4 on 2024-02-10 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0033_alter_bankcards_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onroad',
            name='bank_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_card', to='testApi.bankcards'),
        ),
    ]
