# Generated by Django 4.2.4 on 2024-02-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0034_alter_bankcards_user_alter_onroad_bank_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onroad',
            name='bank_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testApi.bankcards'),
        ),
    ]
