# Generated by Django 4.2.4 on 2024-02-10 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0036_alter_onroad_bank_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onroad',
            name='bank_card',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testApi.bankcards'),
        ),
    ]
